"""empty message

Revision ID: 159d6ace8a68
Revises: 195b0e297ae8
Create Date: 2018-07-09 10:42:37.600255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159d6ace8a68'
down_revision = '195b0e297ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sec_instances', sa.Column('instance_ipcore', sa.String(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipdhcp', sa.String(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipdmz', sa.String(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipelastic', sa.String(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipnetworkadmin', sa.String(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_iprange', sa.String(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipwebserver', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sec_instances', 'instance_ipwebserver')
    op.drop_column('sec_instances', 'instance_iprange')
    op.drop_column('sec_instances', 'instance_ipnetworkadmin')
    op.drop_column('sec_instances', 'instance_ipelastic')
    op.drop_column('sec_instances', 'instance_ipdmz')
    op.drop_column('sec_instances', 'instance_ipdhcp')
    op.drop_column('sec_instances', 'instance_ipcore')
    # ### end Alembic commands ###
