"""empty message

Revision ID: 195b0e297ae8
Revises: 
Create Date: 2018-07-08 06:41:10.897055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195b0e297ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cat_name')
    )
    op.create_table('sec_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_desc', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(length=60), nullable=True),
    sa.Column('industry_core', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['industry_core'], ['sec_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_name')
    )
    op.create_table('sec_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_shortname', sa.String(length=60), nullable=True),
    sa.Column('task_function', sa.String(length=60), nullable=True),
    sa.Column('task_filename', sa.String(length=60), nullable=True),
    sa.Column('task_purpose', sa.String(length=128), nullable=True),
    sa.Column('task_catid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_catid'], ['sec_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sec_task_task_shortname'), 'sec_task', ['task_shortname'], unique=True)
    op.create_table('sec_organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_email', sa.String(length=60), nullable=True),
    sa.Column('org_phone', sa.String(length=60), nullable=True),
    sa.Column('org_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('org_sizeid', sa.Integer(), nullable=True),
    sa.Column('org_industryid', sa.Integer(), nullable=True),
    sa.Column('org_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_industryid'], ['sec_industry.id'], ),
    sa.ForeignKeyConstraint(['org_sizeid'], ['sec_size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sec_organisation_org_email'), 'sec_organisation', ['org_email'], unique=True)
    op.create_index(op.f('ix_sec_organisation_org_name'), 'sec_organisation', ['org_name'], unique=False)
    op.create_index(op.f('ix_sec_organisation_org_phone'), 'sec_organisation', ['org_phone'], unique=False)
    op.create_table('sec_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('project_details', sa.String(length=128), nullable=True),
    sa.Column('project_industryid', sa.Integer(), nullable=True),
    sa.Column('project_datesetup', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('project_status', sa.String(length=128), nullable=True),
    sa.Column('project_orgid', sa.Integer(), nullable=True),
    sa.Column('project_ip', sa.String(length=50), nullable=True),
    sa.Column('project_netip', sa.String(length=50), nullable=True),
    sa.Column('project_netos', sa.String(length=50), nullable=True),
    sa.Column('project_bandwidth_delay', sa.Integer(), nullable=True),
    sa.Column('project_totalnodes', sa.Integer(), nullable=True),
    sa.Column('project_corenodes', sa.Integer(), nullable=True),
    sa.Column('project_coreos', sa.String(length=50), nullable=True),
    sa.Column('project_generalnodes', sa.Integer(), nullable=True),
    sa.Column('project_generalos', sa.String(length=50), nullable=True),
    sa.Column('project_extratraffic', sa.Integer(), nullable=True),
    sa.Column('project_firewallin', sa.String(length=100), nullable=True),
    sa.Column('project_firewallout', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_industryid'], ['sec_industry.id'], ),
    sa.ForeignKeyConstraint(['project_orgid'], ['sec_organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sec_project_project_name'), 'sec_project', ['project_name'], unique=False)
    op.create_table('sec_instances',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('instance_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('instance_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('instance_projectid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_projectid'], ['sec_project.id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sec_instances')
    op.drop_index(op.f('ix_sec_project_project_name'), table_name='sec_project')
    op.drop_table('sec_project')
    op.drop_index(op.f('ix_sec_organisation_org_phone'), table_name='sec_organisation')
    op.drop_index(op.f('ix_sec_organisation_org_name'), table_name='sec_organisation')
    op.drop_index(op.f('ix_sec_organisation_org_email'), table_name='sec_organisation')
    op.drop_table('sec_organisation')
    op.drop_index(op.f('ix_sec_task_task_shortname'), table_name='sec_task')
    op.drop_table('sec_task')
    op.drop_table('sec_industry')
    op.drop_table('sec_size')
    op.drop_table('sec_category')
    # ### end Alembic commands ###
