"""empty message

Revision ID: 4e8f0577547e
Revises: 6eb0d632104d
Create Date: 2018-07-22 22:42:12.280229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8f0577547e'
down_revision = '6eb0d632104d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sec_industry', sa.Column('industry_serverip', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sec_industry', 'industry_serverip')
    # ### end Alembic commands ###
