"""empty message

Revision ID: 7f848666fd4f
Revises: 4e8f0577547e
Create Date: 2018-08-08 14:27:42.412349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f848666fd4f'
down_revision = '4e8f0577547e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sec_instances', 'instance_ipnetworkadmin')
    op.drop_column('sec_instances', 'instance_iprange')
    op.drop_column('sec_instances', 'instance_ipcore')
    op.drop_column('sec_instances', 'instance_ipdhcp')
    op.drop_column('sec_instances', 'instance_ipwebserver')
    op.drop_column('sec_instances', 'instance_ipdmz')
    op.drop_column('sec_instances', 'instance_ipelastic')
    op.add_column('sec_project', sa.Column('collection_pointip', sa.String(length=100), nullable=True))
    op.add_column('sec_project', sa.Column('insider_threat', sa.Integer(), nullable=True))
    op.add_column('sec_project', sa.Column('outsider_threat', sa.Integer(), nullable=True))
    op.drop_column('sec_project', 'project_firewallin')
    op.drop_column('sec_project', 'project_firewallout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sec_project', sa.Column('project_firewallout', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('sec_project', sa.Column('project_firewallin', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('sec_project', 'outsider_threat')
    op.drop_column('sec_project', 'insider_threat')
    op.drop_column('sec_project', 'collection_pointip')
    op.add_column('sec_instances', sa.Column('instance_ipelastic', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipdmz', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipwebserver', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipdhcp', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipcore', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_iprange', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('sec_instances', sa.Column('instance_ipnetworkadmin', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
