"""empty message

Revision ID: 97a7017b4bfb
Revises: 159d6ace8a68
Create Date: 2018-07-09 12:07:01.724761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97a7017b4bfb'
down_revision = '159d6ace8a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sec_instances', 'instance_start',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sec_instances', 'instance_start',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
