"""empty message

Revision ID: d7bfc69b0142
Revises: 39b1ddeecec1
Create Date: 2018-08-21 04:18:03.787656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bfc69b0142'
down_revision = '39b1ddeecec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sec_category', sa.Column('cat_publish', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sec_category', 'cat_publish')
    # ### end Alembic commands ###
